### ISSUE TITLE
MinMax.py unable to handle empty cell

### ISSUE THREAD

**Issue by ms0185** [srp112/GDD_Project#4]
1.If a csv file has null(no data, balnk space) in min/max column, it throws error -
       ValueError: could not convert string to float: 

2.This program is based on cities.txt file, if there is large number of cities, it will open all the csv and calculate/draw plot for each city separately. For minimum of 3, an argument based implementation is needed.

**Comment by ms0185** [comment]
blank space issue resolved

**Comment by uzipaz** [comment]
About blank spaces, this is just how the data is, there are random rows with either missing max temp or min temp, or, both. In order to get around this gap, you can either fill the missing cell by the average of the row above and below it, or you can just ignore it. 

The user has the choice of giving number of cities in the filesas he desires. 1, 3 or more. I don't think that you need to worry about having arguments, just take all the cities from the file and plot them together?

**Comment by fmkazemi** [comment]
I think for this case, one of the best ways  for solving missing data is removing them. Because mean is not logical specially for this case.
Sincerely,
Farhad

**Comment by ms0185** [comment]
1. Resolved
2. Overriding with all the cities in Cities.txt

This issue is closed now
